name: Compilation check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer les dépendences
        run: sudo apt update && sudo apt install -y gcc make clang

      - name: Compiler le projet
        run: make